
# Консоль: DEBUG+
writer1 = console
writer1.level = info 
writer1.format = {date: HH:mm:ss.SSS} [{level}] [req:{context:requestId}] {message}

# Файл: INFO+
writer2 = file
writer2.level = debug
writer2.file = logs/client.log
writer2.format = {date: yyyy-MM-dd HH:mm:ss} [{level}] [req:{context:requestId}] [{thread}] {class}.{method}: {message}
writer2.policies = size(10 MB), daily
writer2.backup_count = 14